---

- name: Including variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
  when: ssh_config is not defined
